// 功能类型，发送验证码的时候需要
export const FUNCTION_TYPE_REG = 1
export const FUNCTION_TYPE_GET_BACK_PASSWORD = 2
export const FUNCTION_TYPE_CHANGE_PASSWORD = 3
export const FUNCTION_TYPE_CHANGE_PHONE_NUMBER = 4
export const FUNCTION_TYPE_CHANGE_EMAIL = 5
export const FUNCTION_TYPE_CHANGE_USERNAME = 6
export const FUNCTION_TYPE_RESET_PASSWORD = 7
export const FUNCTION_TYPE_SET_QUESTION = 8
